name: Build and analyze

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9.1
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
